# Generated by Django 5.1.7 on 2025-03-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_policyversion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policyversion',
            options={'verbose_name': 'Policy Version', 'verbose_name_plural': 'Policy Versions'},
        ),
    ]
