# Generated by Django 5.1.7 on 2025-03-21 15:10

import chatbot.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_policyacceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to=chatbot.models.audio_file_path)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('transcription_model', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_messages', to='chatbot.message')),
            ],
            options={
                'verbose_name': 'Audio Message',
                'verbose_name_plural': 'Audio Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
