# Generated by Django 5.1.7 on 2025-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_audiomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texto'), ('audio', 'Audio'), ('image', 'Imagen'), ('location', 'Ubicación'), ('interactive', 'Interactivo')], default='text', max_length=20),
        ),
    ]
