# Generated by Django 5.1.7 on 2025-03-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default='es', help_text='Código ISO del idioma preferido', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='waiting_for_language',
            field=models.BooleanField(default=False, help_text='Indica si el usuario está esperando seleccionar un idioma'),
        ),
    ]
