# Generated by Django 5.1.7 on 2025-03-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_user_language_user_waiting_for_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, default=None, help_text='Código ISO del idioma preferido', max_length=10),
        ),
    ]
