# Generated by Django 5.1.7 on 2025-03-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_session_analysis_results_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatistics',
            fields=[
            ],
            options={
                'verbose_name': 'Estadísticas de Leads',
                'verbose_name_plural': 'Estadísticas de Leads',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatbot.session',),
        ),
    ]
