# Generated by Django 5.1.7 on 2025-03-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_leadstatistics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leadstatistics',
            options={'verbose_name': 'Lead Statistics', 'verbose_name_plural': 'Lead Statistics'},
        ),
    ]
