# Generated by Django 5.1.7 on 2025-03-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_session_feedback_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='feedback_comment',
            field=models.TextField(blank=True, help_text='Comentario adicional proporcionado como feedback', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='feedback_comment_requested',
            field=models.BooleanField(default=False, help_text='Indica si se solicitó un comentario adicional'),
        ),
        migrations.AddField(
            model_name='session',
            name='feedback_received_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo se recibió el feedback', null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='feedback_response',
            field=models.CharField(blank=True, help_text='Tipo de feedback: positive, negative, comment, etc.', max_length=20, null=True),
        ),
    ]
