# Generated by Django 5.1.7 on 2025-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0020_session_feedback_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='farewell_message_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió un mensaje de despedida'),
        ),
    ]
