# Generated by Django 5.1.7 on 2025-03-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0022_alter_feedback_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.CharField(choices=[('positive', 'Positivo'), ('negative', 'Negativo'), ('neutral', 'Neutral'), ('comment', 'Comentario'), ('comment_requested', 'Comentario Solicitado')], max_length=20),
        ),
    ]
