# Generated by Django 5.1.7 on 2025-03-25 18:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_alter_company_options_company_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIMonthlySummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Año')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('total_requests', models.IntegerField(default=0, verbose_name='Total de solicitudes')),
                ('total_tokens_input', models.IntegerField(default=0, verbose_name='Total tokens de entrada')),
                ('total_tokens_output', models.IntegerField(default=0, verbose_name='Total tokens de salida')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='Total de tokens')),
                ('total_cost_input', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste total entrada ($)')),
                ('total_cost_output', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste total salida ($)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Coste total ($)')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_monthly_summaries', to='chatbot.company')),
            ],
            options={
                'verbose_name': 'Resumen mensual de OpenAI',
                'verbose_name_plural': 'Resúmenes mensuales de OpenAI',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OpenAIUsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('tokens_input', models.IntegerField(default=0, verbose_name='Tokens de entrada')),
                ('tokens_output', models.IntegerField(default=0, verbose_name='Tokens de salida')),
                ('tokens_total', models.IntegerField(default=0, verbose_name='Total de tokens')),
                ('cached_request', models.BooleanField(default=False, verbose_name='Solicitud cacheada')),
                ('cost_input', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Coste de entrada ($)')),
                ('cost_output', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Coste de salida ($)')),
                ('cost_total', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='Coste total ($)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openai_usage_records', to='chatbot.company')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_usages', to='chatbot.session')),
            ],
            options={
                'verbose_name': 'Registro de uso de OpenAI',
                'verbose_name_plural': 'Registros de uso de OpenAI',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['company', 'timestamp'], name='chatbot_ope_company_9c107f_idx'), models.Index(fields=['timestamp'], name='chatbot_ope_timesta_545c4f_idx')],
            },
        ),
    ]
