# Generated by Django 5.1.7 on 2025-03-26 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0027_ticketcategory_ticket_ticketcomment_ticketimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnalysisPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre descriptivo de este prompt', max_length=100)),
                ('prompt_text', models.TextField(help_text='Texto del prompt para analizar imágenes')),
                ('is_default', models.BooleanField(default=False, help_text='Indica si es el prompt predeterminado para la empresa')),
                ('model', models.CharField(default='gpt-4o', help_text='Modelo de IA a utilizar', max_length=50)),
                ('max_tokens', models.IntegerField(default=500, help_text='Tokens máximos para la respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Categoría específica (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_prompts', to='chatbot.ticketcategory')),
                ('company', models.ForeignKey(help_text='Empresa a la que pertenece este prompt', on_delete=django.db.models.deletion.CASCADE, related_name='image_prompts', to='chatbot.company')),
            ],
            options={
                'verbose_name': 'Prompt de Análisis de Imagen',
                'verbose_name_plural': 'Prompts de Análisis de Imagen',
                'unique_together': {('company', 'category', 'is_default')},
            },
        ),
    ]
