# Generated by Django 5.1.7 on 2025-03-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0028_imageanalysisprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketimage',
            name='whatsapp_media_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='ticketimage',
            unique_together={('ticket', 'whatsapp_media_id')},
        ),
    ]
